alter session set "_ORACLE_SCRIPT"= true;

DROP DATABASE LINK Pau_link2;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER Cergy CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER Pau CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

DROP TABLESPACE stockagePau
    INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE stockageCergy
    INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

drop role super_admin;

drop role local_admin;
